version: '2.1'
orbs:
  browser-tools: circleci/browser-tools@2 # https://circleci.com/developer/orbs/orb/circleci/browser-tools
jobs:
  test:
    docker:
      - image: cimg/node:22.17.0-browsers
    steps:
      - checkout
      - run:
          npm ci --frozen-lockfile
      - browser-tools/install_chrome
      - run:
          npx cypress info
      - run:
          google-chrome --version
      - run:
          npx cypress run --browser chrome
workflows:
  test-workflow:
    jobs:
      - test
