version: '2.1'
orbs:
  browser-tools: circleci/browser-tools@2.1.0
jobs:
  test:
    docker:
      - image: cimg/node:22.16.0-browsers
    steps:
      - checkout
      - run:
          npm ci --frozen-lockfile
      - browser-tools/install_browser_tools:
          install_chrome_for_testing: true
          install_edge: true
      - run:
          npx cypress info
      - run:
          DEBUG=cypress:launcher:*,cypress-verbose:launcher:* npx cypress info
      - run:
          google-chrome --version
      - run:
          chrome --version || true
workflows:
  test-workflow:
    jobs:
      - test
