version: '2.1'
orbs:
  browser-tools: circleci/browser-tools@2
jobs:
  test:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - browser-tools/install_chrome_for_testing
      - run:
          name: show installation files
          command: |
            ls -al /usr/local/bin
      - run:
          chrome --version
workflows:
  test-workflow:
    jobs:
      - test
