version: '2.1'
orbs:
  browser-tools: circleci/browser-tools@2
jobs:
  test:
    docker:
      - image: cimg/node:22.17.0-browsers
    steps:
      - checkout
      - run:
          npm ci --frozen-lockfile
      - browser-tools/install_chrome_for_testing
      - run:
          npx cypress info
      - run:
          name: show installation files
          command: |
            ls -al /usr/local/bin
      - run:
          chrome --version
      - run:
          npx cypress run --browser chrome-for-testing
workflows:
  test-workflow:
    jobs:
      - test
