version: '2.1'
orbs:
  browser-tools: circleci/browser-tools@1.5.3 # https://circleci.com/developer/orbs/orb/circleci/browser-tools
jobs:
  test:
    docker:
      - image: cimg/node:22.18.0-browsers
    steps:
      - checkout
      - run:
          npm ci --frozen-lockfile
      - browser-tools/install-browser-tools
      - run:
          npx cypress info
      - run:
          google-chrome --version
      - run:
          chrome --version
      - run:
          microsoft-edge --version
      - run:
          firefox --version
workflows:
  test-workflow:
    jobs:
      - test
