version: '2.1'
orbs:
  browser-tools: circleci/browser-tools@2
jobs:
  test:
    docker:
      - image: cimg/node:22.16.0-browsers
    steps:
      - checkout
      - run:
          npm ci --frozen-lockfile
      - browser-tools/install_edge
      - run:
          npx cypress info
      - run:
          DEBUG=cypress:launcher:*,cypress-verbose:launcher:* npx cypress info
      - run:
          name: show installation files
          command: |
            ls -al /usr/bin | grep edge
            ls -al /etc/alternatives/microsoft-edge
      - run:
          microsoft-edge --version
      - run:
          npx cypress run --browser edge
workflows:
  test-workflow:
    jobs:
      - test
