version: '2.1'
orbs:
  browser-tools: circleci/browser-tools@2 # https://circleci.com/developer/orbs/orb/circleci/browser-tools
jobs:
  test:
    macos:
      xcode: 26.2.0
    steps:
      - checkout
      - run:
          npm ci
      - browser-tools/install_chrome_for_testing:
          version: latest
      - run:
          npx cypress info
      - run:
          name: show installation files
          command: |
            ls -al /usr/local/bin
      - run:
          chrome --version
      - run:
          npx cypress run --browser chrome-for-testing
workflows:
  test-workflow:
    jobs:
      - test
